### PR TITLE
Add detailed configuration example for most topics

### PR DESCRIPTION
**Pull request by DCSBL**
It is not possible to suggest changes to the wiki, so here is a new file. Feel free to copy it into the wiki if you wish.

This is my configuration for most things exposed by the add-on. Some things are not working quite well but it is a start. Nicest thing is the addition of correct `device_classes`, allowing some automatic details from HA.

### CODE REVIEW

**Comment by DCSBL** [comment]
And with a bit of frontend yaml it looks like this (using [Mushroom 🍄](https://github.com/piitaya/lovelace-mushroom)):

Screenshot 2023-06-15 at 13 35 20

Thank you so much for all the research in the API 🙏

**Comment by Eirheim-Home** [comment]
Thank you so much, I have been looking high and low for exactly this (configuration.yaml example) :-) and it works most parts for me/my home assistant.

**Comment by nanomad** [comment]
If you need a dashboard sample:

https://gist.github.com/nanomad/dfadc32502ba73e75a6a88176a0d6404

**Comment by Tonno87** [comment]
Hi, i'm very busy at the moment... But will look into this next weekend 👍

**Comment by DreamT80** [comment]
This is a great initiative. I just want to add something that I've done. I'm not sure if this is the correct way to do it, but it works good for me atleast.

What I've done is that I've added a "device"-section to every entity. This allows me to group the entities to the device it belongs do (i.e., the car itself).

`      device:
           identifiers: "mgzsev"
           manufacturer: "SAIC"
           model: "MG ZS EV"
           name: "Bil"
           hw_version: "MY2022"`

...which then groups the entities with the same device values under the same device in HA. See screenshots.

My naming maybe isn't optimal (and also, I run HA in Swedish, so there is some borking in there), but with the right naming it might come useful.

bil2
bil

**Comment by Tonno87** [comment]
With python gateway 0.3.0 there is a new feature called auto discovery. So it looks like this:
Screenshot 2023-07-30 12 41 00

**Comment by DCSBL** [comment]
Yes, absolutely amazing. No need to manually configure the car in YAML, so closing this one!

**Pull request closed without merging**
